"""
Utility modules for Hcode.
"""

from hcode.utils.config import (
    load_config,
    save_config,
    create_default_config,
    get_project_instructions,
    get_model_for_size,
    MODEL_SIZE_MAP,
    OPENAI_COMPATIBLE_MODELS,
)

from hcode.utils.formatting import (
    console,
    StatusType,
    ICONS,
    get_icon,
    format_status,
    print_success,
    print_error,
    print_warning,
    print_info,
    print_debug,
    render_code,
    render_markdown,
    render_panel,
    create_table,
    create_progress,
    spinner,
    live_display,
    format_tokens,
    format_cost,
    format_duration,
    format_file_path,
    format_diff_stats,
    print_banner,
    print_welcome_tips,
    truncate_text,
    wrap_in_panel,
)

from hcode.utils.validators import (
    ValidationError,
    ValidationResult,
    validate_file_path,
    validate_api_key,
    validate_model_name,
    validate_prompt,
    validate_temperature,
    validate_max_tokens,
    validate_url,
    validate_session_id,
    validate_command,
    validate_glob_pattern,
    sanitize_filename,
    is_safe_path,
)

__all__ = [
    # Config
    "load_config",
    "save_config",
    "create_default_config",
    "get_project_instructions",
    "get_model_for_size",
    "MODEL_SIZE_MAP",
    "OPENAI_COMPATIBLE_MODELS",
    # Formatting
    "console",
    "StatusType",
    "ICONS",
    "get_icon",
    "format_status",
    "print_success",
    "print_error",
    "print_warning",
    "print_info",
    "print_debug",
    "render_code",
    "render_markdown",
    "render_panel",
    "create_table",
    "create_progress",
    "spinner",
    "live_display",
    "format_tokens",
    "format_cost",
    "format_duration",
    "format_file_path",
    "format_diff_stats",
    "print_banner",
    "print_welcome_tips",
    "truncate_text",
    "wrap_in_panel",
    # Validators
    "ValidationError",
    "ValidationResult",
    "validate_file_path",
    "validate_api_key",
    "validate_model_name",
    "validate_prompt",
    "validate_temperature",
    "validate_max_tokens",
    "validate_url",
    "validate_session_id",
    "validate_command",
    "validate_glob_pattern",
    "sanitize_filename",
    "is_safe_path",
]
