"""
Integration test for AI-powered walkthrough.md generation.

Tests that walkthrough is generated using the GPT OSS 120B optimized prompt.
"""
import pytest
from pathlib import Path
from unittest.mock import Mock, AsyncMock, MagicMock

from hcode.core.protocols import AgentContext
from hcode.core.services.artifact_manager import ArtifactManager
from hcode.core.phases.verification_handler import VerificationPhaseHandler


@pytest.fixture
def mock_context(tmp_path):
    """Create a mock agent context."""
    context = AgentContext(
        task="Add user authentication with JWT tokens",
        session_id="test-session-walkthrough",
        working_dir=str(tmp_path),
        iteration=1,
    )
    context.modified_files = [
        str(tmp_path / "src" / "auth.py"),
        str(tmp_path / "tests" / "test_auth.py")
    ]
    context.completed_actions = [
        {"tool": "Write", "success": True},
        {"tool": "Edit", "success": True},
        {"tool": "Bash", "success": True},
    ]
    return context


@pytest.fixture
def artifact_manager(tmp_path):
    """Create an artifact manager with temp directory."""
    return ArtifactManager(artifacts_dir=".hcode")


@pytest.fixture
def mock_provider():
    """Create a mock AI provider that returns a formatted walkthrough."""
    provider = AsyncMock()

    # Mock response with proper format
    mock_response = """<thinking>
Analyzing the input data:
- Task: Add user authentication with JWT tokens
- Files: auth.py, test_auth.py
- Tests: 8 passed, 0 failed
- Verdict: APPROVED

Planning walkthrough structure:
1. Brief task summary
2. Changes with file links
3. Test results
4. Verdict
</thinking>

<output>
# Implementation Walkthrough

## Task Summary
Added user authentication feature with JWT token support. Implementation includes login/logout endpoints, token validation middleware, and comprehensive test coverage.

## Changes Made
- [auth.py](file:///D:/test/src/auth.py) - JWT authentication logic and endpoints
- [test_auth.py](file:///D:/test/tests/test_auth.py) - Authentication test suite

## Verification Results
All authentication tests passed successfully.

**Tests Passed:** 8/8
**Tests Failed:** 0

## Final Verdict
**APPROVED**

---
*Generated by Hcode Verification — 5-Phase QA Protocol*
</output>
"""

    provider.generate = AsyncMock(return_value=mock_response)
    return provider


class TestWalkthroughGeneration:
    """Test AI-powered walkthrough generation."""

    @pytest.mark.asyncio
    async def test_walkthrough_uses_ai_generation(self, mock_context, artifact_manager, mock_provider):
        """Should use AI to generate walkthrough with GPT OSS 120B protocol."""
        handler = VerificationPhaseHandler(
            artifact_manager=artifact_manager,
            provider=mock_provider,
            tool_executor=Mock(),
            context_manager=Mock(),
            console=None
        )

        test_results = {
            "tests_run": True,
            "tests_passed": 8,
            "tests_failed": 0,
            "test_command": "pytest tests/test_auth.py -v",
            "output": "All tests passed"
        }

        verification_analysis = "Implementation follows graceful degradation patterns."

        # Generate walkthrough
        walkthrough = await handler._create_walkthrough(
            mock_context, test_results, verification_analysis
        )

        # Verify AI provider was called
        assert mock_provider.generate.called
        call_args = mock_provider.generate.call_args

        # Verify prompt contains protocol
        prompt = call_args[1]["messages"][0]["content"]
        assert "GPT OSS 120B" in prompt
        assert "walkthrough" in prompt.lower()
        assert "INPUT DATA" in prompt

        # Verify walkthrough content
        assert "# Implementation Walkthrough" in walkthrough
        assert "Task Summary" in walkthrough
        assert "Changes Made" in walkthrough
        assert "Verification Results" in walkthrough
        assert "Final Verdict" in walkthrough
        assert "APPROVED" in walkthrough

    @pytest.mark.asyncio
    async def test_walkthrough_extracts_from_output_tags(self, mock_context, artifact_manager, mock_provider):
        """Should extract walkthrough content from <output> tags."""
        handler = VerificationPhaseHandler(
            artifact_manager=artifact_manager,
            provider=mock_provider,
            tool_executor=Mock(),
            context_manager=Mock(),
            console=None
        )

        test_results = {
            "tests_run": True,
            "tests_passed": 5,
            "tests_failed": 0,
        }

        walkthrough = await handler._create_walkthrough(
            mock_context, test_results, ""
        )

        # Should extract content from <output> tags
        assert "<thinking>" not in walkthrough
        assert "<output>" not in walkthrough
        assert "# Implementation Walkthrough" in walkthrough

    @pytest.mark.asyncio
    async def test_walkthrough_input_data_formatting(self, mock_context, artifact_manager):
        """Should format input data correctly for AI."""
        handler = VerificationPhaseHandler(
            artifact_manager=artifact_manager,
            provider=AsyncMock(),
            tool_executor=Mock(),
            context_manager=Mock(),
            console=None
        )

        test_results = {
            "tests_run": True,
            "tests_passed": 8,
            "tests_failed": 0,
            "test_command": "pytest -v",
        }

        input_data = handler._build_walkthrough_input_data(
            mock_context, test_results, "Analysis here"
        )

        # Verify all required sections
        assert "### Task Description" in input_data
        assert "Add user authentication with JWT tokens" in input_data
        assert "### Modified Files" in input_data
        assert "auth.py" in input_data
        assert "test_auth.py" in input_data
        assert "### Test Results" in input_data
        assert "Tests Passed: 8" in input_data
        assert "Tests Failed: 0" in input_data
        assert "### Verification Analysis" in input_data
        assert "### Completed Actions" in input_data

    @pytest.mark.asyncio
    async def test_walkthrough_fallback_on_error(self, mock_context, artifact_manager):
        """Should use fallback template when AI generation fails."""
        # Mock provider that raises error
        error_provider = AsyncMock()
        error_provider.generate = AsyncMock(side_effect=Exception("API Error"))

        handler = VerificationPhaseHandler(
            artifact_manager=artifact_manager,
            provider=error_provider,
            tool_executor=Mock(),
            context_manager=Mock(),
            console=None
        )

        test_results = {
            "tests_run": True,
            "tests_passed": 5,
            "tests_failed": 0,
        }

        # Should not raise error, use fallback instead
        walkthrough = await handler._create_walkthrough(
            mock_context, test_results, ""
        )

        # Verify fallback was used
        assert "# Implementation Walkthrough" in walkthrough
        assert "Task Summary" in walkthrough
        assert "APPROVED" in walkthrough

    @pytest.mark.asyncio
    async def test_walkthrough_file_links_use_basenames(self, mock_context, artifact_manager, mock_provider):
        """Should use file basenames in link text, not full paths."""
        handler = VerificationPhaseHandler(
            artifact_manager=artifact_manager,
            provider=mock_provider,
            tool_executor=Mock(),
            context_manager=Mock(),
            console=None
        )

        test_results = {"tests_run": False}

        walkthrough = await handler._create_walkthrough(
            mock_context, test_results, ""
        )

        # AI response should use basenames in link text
        assert "[auth.py]" in walkthrough or "auth.py" in walkthrough
        assert "[test_auth.py]" in walkthrough or "test_auth.py" in walkthrough

    def test_extract_walkthrough_from_response(self, artifact_manager):
        """Should extract walkthrough from various response formats."""
        handler = VerificationPhaseHandler(
            artifact_manager=artifact_manager,
            provider=Mock(),
            tool_executor=Mock(),
            context_manager=Mock(),
            console=None
        )

        # Test 1: Extract from <output> tags
        response1 = """<thinking>Analysis...</thinking>
<output>
# Implementation Walkthrough
Content here
</output>"""
        result1 = handler._extract_walkthrough_from_response(response1)
        assert "# Implementation Walkthrough" in result1
        assert "<thinking>" not in result1

        # Test 2: Extract from multiple output tags (use last one)
        response2 = """<output>Draft 1</output>
<thinking>More thinking</thinking>
<output># Implementation Walkthrough
Final version</output>"""
        result2 = handler._extract_walkthrough_from_response(response2)
        assert "Final version" in result2
        assert "Draft 1" not in result2

        # Test 3: Extract from plain markdown (no tags)
        response3 = """# Implementation Walkthrough
Plain content without tags"""
        result3 = handler._extract_walkthrough_from_response(response3)
        assert "# Implementation Walkthrough" in result3


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
