"""
Sub-agent system for Hcode.
Specialized agents for different types of tasks (Explore, Plan, etc.).
"""

import asyncio
from dataclasses import dataclass
from enum import Enum
from typing import Dict, Any, Optional, List

from hcode.providers import AIProvider, Message, ProviderSelector
from hcode.tools.base.base_tool import ToolRegistry


class HcodeAgentType(Enum):
    """
    Google‑style docstring for HcodeAgentType.

    Summary:
        Enum defining the different specialized Hcode agents available in the system.

    Attributes:
        GENERAL (str): General‑purpose agent.
        EXPLORE (str): Agent for exploring codebases.
        PLAN (str): Agent for planning implementations.
        IMPLEMENT (str): Agent for implementing code based on a plan.
        TEST (str): Agent for testing generated code.
        DEBUG (str): Agent for debugging tasks.
        REFACTOR (str): Agent for refactoring code.
    """

    GENERAL = "general-purpose"
    EXPLORE = "Explore"
    PLAN = "Plan"
    IMPLEMENT = "Implement"
    TEST = "Test"
    DEBUG = "Debug"
    REFACTOR = "Refactor"


@dataclass
class HcodeAgentResult:
    """
    Google‑style docstring for HcodeAgentResult.

    Summary:
        Dataclass that encapsulates the result returned by a sub‑agent after executing a task.

    Attributes:
        agent_type (HcodeAgentType): The type of agent that produced this result.
        success (bool): Indicates whether the agent completed the task successfully.
        output (str): The textual output or response generated by the agent.
        metadata (Dict[str, Any]): Additional metadata such as token usage, timestamps, or other contextual information.
        error (Optional[str]): Optional error message if the agent failed; None when there is no error.
    """

    agent_type: HcodeAgentType
    success: bool
    output: str
    metadata: Dict[str, Any]
    error: Optional[str] = None


class HcodeSubAgent:
    """
    Google‑style docstring for HcodeSubAgent.

    Summary:
        Base class that provides common functionality for all specialized Hcode sub‑agents. It manages the agent type, AI provider, tool registry, and conversation history used during execution.

    Attributes:
        agent_type (HcodeAgentType): The specific type of sub‑agent (e.g., EXPLORE, PLAN, IMPLEMENT).
        provider (AIProvider): The AI provider used to generate completions.
        tool_registry (ToolRegistry): Registry of tools available to the agent.
        conversation_history (List[Message]): List of messages exchanged with the AI during the agent's execution.
    """

    def __init__(self, agent_type: HcodeAgentType, provider: AIProvider, tool_registry: ToolRegistry):
        """
        Initialize sub‑agent.

        Summary:
            Sets up the sub‑agent with its type, AI provider, and tool registry.

        Args:
            agent_type (HcodeAgentType): Type of specialized agent.
            provider (AIProvider): AI provider to use.
            tool_registry (ToolRegistry): Available tools.

        Returns:
            None.

        Raises:
            None.
        """
        self.agent_type = agent_type
        self.provider = provider
        self.tool_registry = tool_registry
        self.conversation_history: List[Message] = []

    async def execute(self, task: str, context: Optional[Dict] = None) -> HcodeAgentResult:
        """
        Execute the agent's specialized task.

        Summary:
            Runs the sub‑agent's specific logic for the given task and optional context.
            This base implementation is abstract and must be overridden by concrete agents.

        Args:
            task (str): Task description.
            context (Optional[Dict]): Additional context that may influence execution.

        Returns:
            HcodeAgentResult: Result object containing execution outcome, output, and metadata.

        Raises:
            NotImplementedError: If the concrete sub‑agent does not implement this method.
        """
        raise NotImplementedError

    def _get_system_prompt(self) -> str:
        """
        Get agent‑specific system prompt from external config.

        Summary:
            Loads the base system prompt for the sub‑agent from the configuration module and returns it as a string. Sub‑classes may extend this prompt with additional information.

        Returns:
            str: The complete system prompt for the agent.

        Raises:
            None.
        """
        from ..config.prompts import get_system_prompt

        # Get base prompt from config
        base_prompt = get_system_prompt("sub_agent")

        # Add available tools list
        base_prompt += "\n\nAvailable tools:\n"
        for tool in self.tool_registry.list_tools():
            base_prompt += f"\n- {tool.name}: {tool.get_description()}"

        base_prompt += "\n\nUse these tools to accomplish your task effectively."
        return base_prompt


class HcodeExploreAgent(HcodeSubAgent):
    """
    Agent specialized for exploring codebases.

    Summary:
        Provides functionality to explore the codebase, perform pattern matching, and gather information required by other agents.

    Attributes:
        Inherits attributes from HcodeSubAgent:
            agent_type (HcodeAgentType): The specific type of sub‑agent (EXPLORE).
            provider (AIProvider): The AI provider used to generate completions.
            tool_registry (ToolRegistry): Registry of tools available to the agent.
            conversation_history (List[Message]): List of messages exchanged with the AI.
    """

    def __init__(self, provider: AIProvider, tool_registry: ToolRegistry):
        """
        Initialize the explore sub‑agent.

        Summary:
            Creates an instance of `HcodeExploreAgent` by invoking the base class initializer with the `EXPLORE` agent type, the provided AI provider, and the tool registry.

        Args:
            provider (AIProvider): The AI provider used to generate completions.
            tool_registry (ToolRegistry): Registry of tools available to the agent.

        Returns:
            None.

        Raises:
            None.
        """
        super().__init__(HcodeAgentType.EXPLORE, provider, tool_registry)

    def _get_system_prompt(self) -> str:
        """
        Get explore agent prompt from external config.

        Summary:
            Retrieves the system prompt specific to the explore agent and appends the generic sub‑agent prompt.

        Returns:
            str: Combined system prompt for the explore agent.

        Raises:
            None.
        """
        from ..config.prompts import get_system_prompt
        return get_system_prompt("explore_agent") + super()._get_system_prompt()

    async def execute(self, task: str, context: Optional[Dict] = None) -> HcodeAgentResult:
        """
        Execute exploration task.

        Summary:
            Performs a code‑base exploration based on the provided task description, optionally using a specified thoroughness level.

        Args:
            task (str): Description of what to explore.
            context (Optional[Dict]): Optional context; may contain additional parameters such as `thoroughness`.

        Returns:
            HcodeAgentResult: Result containing the exploration output and metadata.

        Raises:
            Exception: Propagates any unexpected errors during exploration.
        """
        try:
            thoroughness = context.get("thoroughness", "medium") if context else "medium"

            # Build exploration prompt
            prompt = f"""Explore the codebase to answer: {task}\n\nThoroughness level: {thoroughness}\n\nUse Glob and Grep tools to search systematically. Report findings clearly."""

            # Add to conversation
            self.conversation_history.append(Message(role="user", content=prompt))

            # Get system prompt
            system_prompt = self._get_system_prompt()
            messages = [Message(role="system", content=system_prompt)] + self.conversation_history

            # Execute with AI
            response = await self.provider.generate_completion(messages=messages, stream=False)

            return HcodeAgentResult(
                agent_type=self.agent_type,
                success=True,
                output=response.content,
                metadata={"thoroughness": thoroughness, "tokens_used": response.usage.total_tokens},
            )
        except Exception as e:
            return HcodeAgentResult(agent_type=self.agent_type, success=False, output="", metadata={}, error=str(e))


class HcodePlanAgent(HcodeSubAgent):
    """
    Agent specialized for planning implementations.

    Summary:
        Generates detailed, step‑by‑step implementation plans for complex tasks.
    """

    def __init__(self, provider: AIProvider, tool_registry: ToolRegistry):
        super().__init__(HcodeAgentType.PLAN, provider, tool_registry)

    def _get_system_prompt(self) -> str:
        """
        Get plan agent prompt from external config.

        Summary:
            Retrieves the system prompt specific to the planning agent and appends the generic sub‑agent prompt.

        Returns:
            str: Combined system prompt for the planning agent.

        Raises:
            None.
        """
        from ..config.prompts import get_system_prompt
        return get_system_prompt("plan_agent") + super()._get_system_prompt()

    async def execute(self, task: str, context: Optional[Dict] = None) -> HcodeAgentResult:
        """
        Create implementation plan.

        Summary:
            Generates a comprehensive implementation plan for the given task, optionally using prior exploration results.

        Args:
            task (str): Description of the implementation goal.
            context (Optional[Dict]): May contain `explore_first` flag and exploration output.

        Returns:
            HcodeAgentResult: Result containing the generated plan and metadata.

        Raises:
            Exception: Propagates any unexpected errors during planning.
        """
        try:
            # Explore codebase first if needed
            if context and context.get("explore_first", True):
                explore_agent = HcodeExploreAgent(self.provider, self.tool_registry)
                explore_result = await explore_agent.execute(
                    f"Understand the codebase structure for: {task}", {"thoroughness": "quick"}
                )
                codebase_context = explore_result.output
            else:
                codebase_context = "No prior exploration"

            # Build planning prompt
            prompt = f"""Create a detailed implementation plan for: {task}\n\nCodebase context:\n{codebase_context}\n\nProvide:\n1. High-level approach\n2. Step-by-step breakdown\n3. Files to create/modify\n4. Dependencies and risks\n5. Testing strategy"""

            self.conversation_history.append(Message(role="user", content=prompt))
            system_prompt = self._get_system_prompt()
            messages = [Message(role="system", content=system_prompt)] + self.conversation_history
            response = await self.provider.generate_completion(messages=messages, stream=False)

            return HcodeAgentResult(
                agent_type=self.agent_type,
                success=True,
                output=response.content,
                metadata={"tokens_used": response.usage.total_tokens, "explored_first": context.get("explore_first", True) if context else True},
            )
        except Exception as e:
            return HcodeAgentResult(agent_type=self.agent_type, success=False, output="", metadata={}, error=str(e))


class HcodeImplementAgent(HcodeSubAgent):
    """
    Agent specialized for code implementation.
    Writes production-quality code based on plans.
    """

    def __init__(self, provider: AIProvider, tool_registry: ToolRegistry):
        """
        Initialize implementation agent.

        Summary:
            Creates an instance of `HcodeImplementAgent` with the IMPLEMENT agent type.

        Args:
            provider (AIProvider): The AI provider used to generate completions.
            tool_registry (ToolRegistry): Registry of tools available to the agent.

        Returns:
            None.

        Raises:
            None.
        """
        super().__init__(HcodeAgentType.IMPLEMENT, provider, tool_registry)

    def _get_system_prompt(self) -> str:
        """
        Get code agent prompt from external config.

        Summary:
            Retrieves the system prompt specific to the implementation agent and appends the generic sub‑agent prompt.

        Returns:
            str: Combined system prompt for the implementation agent.

        Raises:
            None.
        """
        from ..config.prompts import get_system_prompt
        return get_system_prompt("code_agent") + super()._get_system_prompt()

    async def execute(self, task: str, context: Optional[Dict] = None) -> HcodeAgentResult:
        """
        Implement code based on plan.

        Summary:
            Generates production‑quality code for the given task, optionally following a provided implementation plan.

        Args:
            task (str): Description of the coding task.
            context (Optional[Dict]): May contain a `plan` key with a detailed implementation plan.

        Returns:
            HcodeAgentResult: Result containing the generated code and metadata.

        Raises:
            Exception: Propagates any unexpected errors during code generation.
        """
        try:
            plan = context.get("plan", "") if context else ""
            prompt = f"""Implement the following task: {task}\n\n"""
            if plan:
                prompt += f"""Plan to follow:\n{plan}\n\n"""
            prompt += """Write production-quality code using the Write and Edit tools. Include proper error handling, documentation, and tests."""

            self.conversation_history.append(Message(role="user", content=prompt))
            system_prompt = self._get_system_prompt()
            messages = [Message(role="system", content=system_prompt)] + self.conversation_history
            response = await self.provider.generate_completion(messages=messages, stream=False)

            return HcodeAgentResult(
                agent_type=self.agent_type,
                success=True,
                output=response.content,
                metadata={"tokens_used": response.usage.total_tokens, "had_plan": bool(plan)},
            )
        except Exception as e:
            return HcodeAgentResult(agent_type=self.agent_type, success=False, output="", metadata={}, error=str(e))


class HcodeAgentOrchestrator:
    """
    Orchestrates multiple sub‑agents to execute tasks.

    This orchestrator coordinates the execution of various specialized sub‑agents (e.g., explore, plan, implement) either sequentially or in parallel. It selects an appropriate AI provider via the provided `ProviderSelector` and uses the supplied `ToolRegistry` to give agents access to the available tools.

    Attributes:
        provider_selector (ProviderSelector): Selector used to obtain the AI provider for agent execution.
        tool_registry (ToolRegistry): Registry of tools that agents can invoke.
    """

    def __init__(self, provider_selector: ProviderSelector, tool_registry: ToolRegistry):
        """
        Initialize agent orchestrator.

        Args:
            provider_selector: Provider selector for choosing AI providers.
            tool_registry: Available tools.
        """
        self.provider_selector = provider_selector
        self.tool_registry = tool_registry

    async def execute_with_agents(self, task: str, agent_types: List[HcodeAgentType], parallel: bool = False) -> List[HcodeAgentResult]:
        """
        Execute task using multiple agents.

        Summary:
            Runs the specified agents either sequentially or in parallel, passing context between them when appropriate.

        Args:
            task (str): Task description.
            agent_types (List[HcodeAgentType]): Types of agents to use.
            parallel (bool): Execute agents in parallel if True; otherwise sequentially.

        Returns:
            List[HcodeAgentResult]: List of results from each executed agent.
        """
        # Select provider
        provider = self.provider_selector.select_provider()

        # Create agents
        agents = []
        for agent_type in agent_types:
            if agent_type == HcodeAgentType.EXPLORE:
                agents.append(HcodeExploreAgent(provider, self.tool_registry))
            elif agent_type == HcodeAgentType.PLAN:
                agents.append(HcodePlanAgent(provider, self.tool_registry))
            elif agent_type == HcodeAgentType.IMPLEMENT:
                agents.append(HcodeImplementAgent(provider, self.tool_registry))

        # Execute agents
        if parallel:
            # Parallel execution
            tasks = [agent.execute(task) for agent in agents]
            results = await asyncio.gather(*tasks)
        else:
            # Sequential execution with context passing
            results = []
            context = {}
            for agent in agents:
                result = await agent.execute(task, context)
                results.append(result)
                if result.success:
                    if agent.agent_type == HcodeAgentType.EXPLORE:
                        context["exploration"] = result.output
                    elif agent.agent_type == HcodeAgentType.PLAN:
                        context["plan"] = result.output
        return results

    async def auto_execute(self, task: str) -> HcodeAgentResult:
        """
        Automatically determine and execute with appropriate agents.

        Summary:
            Analyzes the task description to decide which agents are needed and runs them sequentially, returning the final result.

        Args:
            task (str): Task description.

        Returns:
            HcodeAgentResult: Final agent result after automatic orchestration.
        """
        # Analyze task to determine agents needed
        if "explore" in task.lower() or "find" in task.lower() or "search" in task.lower():
            agent_types = [HcodeAgentType.EXPLORE]
        elif "plan" in task.lower():
            agent_types = [HcodeAgentType.EXPLORE, HcodeAgentType.PLAN]
        elif "implement" in task.lower() or "create" in task.lower() or "build" in task.lower():
            agent_types = [HcodeAgentType.EXPLORE, HcodeAgentType.PLAN, HcodeAgentType.IMPLEMENT]
        else:
            # Default: explore and plan
            agent_types = [HcodeAgentType.EXPLORE, HcodeAgentType.PLAN]

        # Execute agents sequentially
        results = await self.execute_with_agents(task, agent_types, parallel=False)
        # Return the last result (typically the implementation result if present)
        return results[-1] if results else HcodeAgentResult(agent_type=HcodeAgentType.GENERAL, success=False, output="", metadata={})


""
