#!/usr/bin/env python3
"""
HCode Cython Build Script.

Compiles Python source code to C extensions for protection and performance.

Usage:
    python scripts/build_cython.py           # Build both package and exe
    python scripts/build_cython.py --pkg     # Build only Python package
    python scripts/build_cython.py --exe     # Build only executable
    python scripts/build_cython.py --clean   # Clean build artifacts
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
SRC_DIR = PROJECT_ROOT / "src"
HCODE_SRC = SRC_DIR / "hcode"
DIST_DIR = PROJECT_ROOT / "dist"
BUILD_DIR = PROJECT_ROOT / "build"
CYTHON_BUILD_DIR = BUILD_DIR / "cython_build"


def run_command(cmd: list[str], description: str, cwd: Path | None = None) -> bool:
    """Run a command and return success status."""
    print(f"\n{'='*60}")
    print(f"  {description}")
    print(f"{'='*60}")

    try:
        result = subprocess.run(
            cmd,
            cwd=cwd or PROJECT_ROOT,
            capture_output=False,
            text=True,
        )
        if result.returncode == 0:
            print(f"  [OK] {description}")
            return True
        else:
            print(f"  [FAILED] {description}")
            return False
    except Exception as e:
        print(f"  [ERROR] {e}")
        return False


def clean_source_artifacts():
    """Clean build artifacts from the original source directory (from previous in-place builds)."""
    print("\n  Cleaning source directory artifacts from previous builds...")

    # Clean .c files generated by Cython from source
    c_count = 0
    for c_file in SRC_DIR.rglob("*.c"):
        c_file.unlink()
        c_count += 1
    if c_count:
        print(f"  Removed {c_count} .c files from source directory")

    # Clean compiled extensions from source
    ext_count = 0
    for ext in ["*.pyd", "*.so"]:
        for compiled_file in SRC_DIR.rglob(ext):
            compiled_file.unlink()
            ext_count += 1
    if ext_count:
        print(f"  Removed {ext_count} compiled extensions from source directory")

    # Clean setup_cython.py from project root
    setup_cython = PROJECT_ROOT / "setup_cython.py"
    if setup_cython.exists():
        setup_cython.unlink()
        print(f"  Removed: {setup_cython}")


def clean_build_artifacts():
    """Clean all build artifacts."""
    print("\nCleaning build artifacts...")

    # First clean any artifacts from the source directory (from old in-place builds)
    clean_source_artifacts()

    dirs_to_clean = [
        BUILD_DIR,
        DIST_DIR,
        PROJECT_ROOT / "hcode.egg-info",
    ]

    for dir_path in dirs_to_clean:
        if dir_path.exists():
            shutil.rmtree(dir_path)
            print(f"  Removed: {dir_path}")

    # Clean .spec files
    for spec_file in PROJECT_ROOT.glob("*.spec"):
        spec_file.unlink()
        print(f"  Removed: {spec_file}")

    # Clean __pycache__ directories (but not in .venv)
    for cache_dir in PROJECT_ROOT.rglob("__pycache__"):
        if ".venv" not in str(cache_dir):
            shutil.rmtree(cache_dir)
            print(f"  Removed: {cache_dir}")

    print("  Clean complete!")


def check_cython():
    """Check if Cython is installed and working."""
    try:
        import Cython

        print(f"Cython version: {Cython.__version__}")
        return True
    except ImportError:
        print("ERROR: Cython not installed")
        print("Install with: pip install cython")
        return False


def create_setup_py(build_dir: Path):
    """Create a setup.py for Cython compilation in the build directory."""
    setup_content = '''#!/usr/bin/env python3
"""
Cython setup script for HCode.
This compiles Python files to C extensions.
"""

import os
import sys
from pathlib import Path
from setuptools import setup, find_packages
from Cython.Build import cythonize
from Cython.Distutils import build_ext

# Get the source directory (relative to where this script is placed)
SRC_DIR = Path(__file__).parent / "src"
HCODE_DIR = SRC_DIR / "hcode"

# Files to exclude from Cython compilation (keep as Python)
EXCLUDE_FILES = {
    "__init__.py",  # Keep package init files as Python
    "__main__.py",  # Keep entry points as Python
}

# Directories to exclude entirely
EXCLUDE_DIRS = {
    "__pycache__",
    ".git",
    "tests",
}


def get_python_files():
    """Get list of Python files to compile with Cython."""
    py_files = []

    for py_file in HCODE_DIR.rglob("*.py"):
        # Skip excluded directories
        if any(excluded in py_file.parts for excluded in EXCLUDE_DIRS):
            continue

        # Skip excluded files
        if py_file.name in EXCLUDE_FILES:
            continue

        py_files.append(str(py_file))

    return py_files


def main():
    py_files = get_python_files()

    if not py_files:
        print("No Python files found to compile!")
        sys.exit(1)

    print(f"Compiling {len(py_files)} Python files with Cython...")
    for f in py_files:
        print(f"  - {f}")

    # Cython compiler directives - using safe defaults for compatibility
    compiler_directives = {
        "language_level": "3",
        "boundscheck": True,
        "wraparound": True,
        "initializedcheck": True,
        "cdivision": False,
        "embedsignature": True,
    }

    extensions = cythonize(
        py_files,
        compiler_directives=compiler_directives,
        nthreads=os.cpu_count() or 1,
        quiet=False,
    )

    setup(
        name="hcode",
        version="1.0.0",
        ext_modules=extensions,
        cmdclass={"build_ext": build_ext},
        packages=find_packages(where="src"),
        package_dir={"": "src"},
        zip_safe=False,
    )


if __name__ == "__main__":
    main()
'''

    setup_path = build_dir / "setup_cython.py"
    setup_path.write_text(setup_content)
    print(f"Created: {setup_path}")
    return setup_path


def compile_with_cython():
    """Compile Python source code with Cython in an isolated build directory."""
    print("\n" + "=" * 60)
    print("  Compiling source code with Cython (isolated build)")
    print("=" * 60)

    # Create isolated build directory
    cython_work_dir = CYTHON_BUILD_DIR / "workspace"
    if cython_work_dir.exists():
        shutil.rmtree(cython_work_dir)
    cython_work_dir.mkdir(parents=True, exist_ok=True)

    # Copy source to build directory
    build_src = cython_work_dir / "src"
    print(f"  Copying source to: {build_src}")
    shutil.copytree(SRC_DIR, build_src)

    # Create setup.py in build directory
    setup_path = create_setup_py(cython_work_dir)

    # Run Cython compilation in build directory (not in-place to original source)
    cmd = [
        sys.executable,
        str(setup_path),
        "build_ext",
        "--inplace",
    ]

    print(f"\nRunning: {' '.join(cmd)}")
    print(f"Working directory: {cython_work_dir}")

    result = subprocess.run(
        cmd,
        cwd=cython_work_dir,
        capture_output=False,
    )

    if result.returncode != 0:
        print("ERROR: Cython compilation failed")
        return False

    # Clean up .c files from build directory (keep only .pyd/.so)
    print("\n  Cleaning up intermediate .c files...")
    c_count = 0
    for c_file in build_src.rglob("*.c"):
        c_file.unlink()
        c_count += 1
    print(f"  Removed {c_count} .c files from build directory")

    print("  [OK] Cython compilation complete")
    return True


def get_compiled_extensions_dir() -> Path:
    """Get the directory containing compiled extensions."""
    return CYTHON_BUILD_DIR / "workspace" / "src" / "hcode"


def build_cython_package():
    """Build Python package with Cython-compiled extensions."""
    print("\n" + "=" * 60)
    print("  Building Python Package with Cython Extensions")
    print("=" * 60)

    # Use the compiled code from isolated build directory
    compiled_src = get_compiled_extensions_dir().parent  # src directory
    if not compiled_src.exists():
        print("ERROR: Compiled source not found. Run Cython compilation first.")
        return False

    # Create a build directory for the package
    pkg_build_dir = BUILD_DIR / "pkg_build"
    pkg_build_dir.mkdir(parents=True, exist_ok=True)

    # Copy compiled source directory (already has .pyd/.so files, no .c files)
    dest_src = pkg_build_dir / "src"
    if dest_src.exists():
        shutil.rmtree(dest_src)
    shutil.copytree(compiled_src, dest_src)

    # Remove .py files where compiled extensions exist (keep only __init__.py and __main__.py)
    import platform

    ext = ".pyd" if platform.system().lower() == "windows" else ".so"

    replaced_count = 0
    for compiled_file in dest_src.rglob(f"*{ext}"):
        # Find and remove corresponding .py file
        py_file = compiled_file.with_suffix(".py")
        # Handle the cp311-win_amd64 naming pattern
        if not py_file.exists():
            # Try to find the original .py file name from the .pyd/.so name
            # e.g., cli.cp311-win_amd64.pyd -> cli.py
            stem = compiled_file.stem.split(".")[0]  # Get 'cli' from 'cli.cp311-win_amd64'
            py_file = compiled_file.parent / f"{stem}.py"

        if py_file.exists() and py_file.name not in {"__init__.py", "__main__.py"}:
            py_file.unlink()
            replaced_count += 1
            print(f"  Replaced: {py_file.name} -> {compiled_file.name}")

    print(f"  Replaced {replaced_count} .py files with compiled extensions")

    # Copy pyproject.toml
    shutil.copy(PROJECT_ROOT / "pyproject.toml", pkg_build_dir / "pyproject.toml")

    # Copy README.md if exists
    readme = PROJECT_ROOT / "README.md"
    if readme.exists():
        shutil.copy(readme, pkg_build_dir / "README.md")

    # Build the package
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    compiled_dist = DIST_DIR / "compiled"
    compiled_dist.mkdir(parents=True, exist_ok=True)

    build_cmd = [
        sys.executable,
        "-m",
        "build",
        "--outdir",
        str(compiled_dist),
    ]

    result = subprocess.run(
        build_cmd,
        cwd=pkg_build_dir,
        capture_output=False,
    )

    if result.returncode != 0:
        print("ERROR: Package build failed")
        return False

    print("  [OK] Compiled package built successfully")
    print(f"  Output: {compiled_dist}")
    return True


def build_cython_exe():
    """Build executable from Cython-compiled code using PyInstaller."""
    print("\n" + "=" * 60)
    print("  Building Executable with Cython-Compiled Code")
    print("=" * 60)

    import platform

    system = platform.system().lower()
    machine = platform.machine().lower()

    # Platform info
    if system == "windows":
        platform_name = f"windows-{machine}"
        exe_name = "hcode.exe"
        ext = ".pyd"
    elif system == "darwin":
        platform_name = f"macos-{machine}"
        exe_name = "hcode"
        ext = ".so"
    else:
        platform_name = f"linux-{machine}"
        exe_name = "hcode"
        ext = ".so"

    # Get compiled source from isolated build directory
    compiled_hcode = get_compiled_extensions_dir()
    if not compiled_hcode.exists():
        print("ERROR: Compiled source not found. Run Cython compilation first.")
        return False

    # Create temporary directory for PyInstaller
    exe_build_dir = BUILD_DIR / "exe_build"
    exe_build_dir.mkdir(parents=True, exist_ok=True)

    # Copy compiled hcode package (already has .pyd/.so files, no .c files)
    exe_src = exe_build_dir / "hcode"
    if exe_src.exists():
        shutil.rmtree(exe_src)
    shutil.copytree(compiled_hcode, exe_src)

    # Remove .py files where compiled extensions exist
    replaced_count = 0
    for compiled_file in exe_src.rglob(f"*{ext}"):
        stem = compiled_file.stem.split(".")[0]
        py_file = compiled_file.parent / f"{stem}.py"
        if py_file.exists() and py_file.name not in {"__init__.py", "__main__.py"}:
            py_file.unlink()
            replaced_count += 1

    print(f"  Prepared {replaced_count} compiled extensions for packaging")

    # Create entry point script
    entry_point = exe_build_dir / "hcode_main.py"
    entry_point.write_text(
        '''#!/usr/bin/env python3
"""HCode entry point for PyInstaller."""
import sys
import os

# Add the current directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from hcode.cli_enhanced import main

if __name__ == "__main__":
    main()
'''
    )

    # Hidden imports for PyInstaller
    hidden_imports = [
        "tiktoken_ext.openai_public",
        "tiktoken_ext",
        "anthropic",
        "anthropic._streaming",
        "openai",
        "openai._streaming",
        "rich",
        "rich.console",
        "rich.markdown",
        "rich.syntax",
        "pydantic",
        "pydantic_settings",
        "httpx",
        "httpcore",
        "yaml",
        "dotenv",
        "click",
        "pygments",
        "prompt_toolkit",
        "tenacity",
        "aiofiles",
        "encodings",
        "encodings.utf_8",
    ]

    collect_packages = [
        "anthropic",
        "openai",
        "tiktoken",
        "rich",
        "pydantic",
        "pygments",
        "httpx",
    ]

    # Output directory
    output_dir = DIST_DIR / "compiled" / platform_name
    output_dir.mkdir(parents=True, exist_ok=True)

    # Build PyInstaller command
    cmd = [
        sys.executable,
        "-m",
        "PyInstaller",
        str(entry_point),
        f"--name=hcode",
        f"--distpath={output_dir}",
        f"--workpath={BUILD_DIR / 'pyinstaller'}",
        "--onefile",
        "--console",
        "--clean",
        "--noconfirm",
    ]

    # Add hidden imports
    for imp in hidden_imports:
        cmd.extend(["--hidden-import", imp])

    # Add collect-all for packages
    for pkg in collect_packages:
        cmd.extend(["--collect-all", pkg])

    # Add the hcode package with compiled extensions
    separator = ";" if system == "windows" else ":"
    cmd.extend(["--add-data", f"{exe_src}{separator}hcode"])

    print(f"Building executable for: {platform_name}")

    result = subprocess.run(
        cmd,
        cwd=exe_build_dir,
        capture_output=False,
    )

    if result.returncode != 0:
        print("ERROR: Executable build failed")
        return False

    # Move exe to final location (PyInstaller puts it in a subdirectory)
    built_exe = output_dir / "hcode" / exe_name
    if built_exe.exists():
        final_exe = output_dir / exe_name
        shutil.move(str(built_exe), str(final_exe))
        # Clean up empty directory
        (output_dir / "hcode").rmdir()

    print("  [OK] Executable built successfully")
    print(f"  Output: {output_dir / exe_name}")
    return True


def verify_builds():
    """Verify that the builds work correctly."""
    print("\n" + "=" * 60)
    print("  Verifying Builds")
    print("=" * 60)

    import platform

    system = platform.system().lower()
    machine = platform.machine().lower()

    if system == "windows":
        platform_name = f"windows-{machine}"
        exe_name = "hcode.exe"
    elif system == "darwin":
        platform_name = f"macos-{machine}"
        exe_name = "hcode"
    else:
        platform_name = f"linux-{machine}"
        exe_name = "hcode"

    all_passed = True

    # Verify executable
    exe_path = DIST_DIR / "compiled" / platform_name / exe_name
    if exe_path.exists():
        print(f"\nVerifying executable: {exe_path}")
        print(f"  Size: {exe_path.stat().st_size / (1024*1024):.2f} MB")

        try:
            result = subprocess.run(
                [str(exe_path), "--version"],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                print(f"  Version check: [OK]")
                print(f"  Output: {result.stdout.strip()}")
            else:
                print(f"  Version check: [FAILED]")
                print(f"  Error: {result.stderr}")
                all_passed = False
        except subprocess.TimeoutExpired:
            print("  Version check: [TIMEOUT]")
            all_passed = False
        except Exception as e:
            print(f"  Version check: [ERROR] {e}")
            all_passed = False

        # Test --help
        try:
            result = subprocess.run(
                [str(exe_path), "--help"],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0 and "hcode" in result.stdout.lower():
                print(f"  Help check: [OK]")
            else:
                print(f"  Help check: [FAILED]")
                all_passed = False
        except Exception as e:
            print(f"  Help check: [ERROR] {e}")
            all_passed = False
    else:
        print(f"  Executable not found: {exe_path}")
        all_passed = False

    # Verify package
    pkg_dir = DIST_DIR / "compiled"
    if pkg_dir.exists():
        wheel_files = list(pkg_dir.glob("*.whl"))
        tar_files = list(pkg_dir.glob("*.tar.gz"))

        if wheel_files:
            print(f"\nVerifying package: {wheel_files[0].name}")
            print(f"  Size: {wheel_files[0].stat().st_size / 1024:.2f} KB")
            print(f"  Package check: [OK]")
        else:
            print("  No wheel package found")

        if tar_files:
            print(f"  Source dist: {tar_files[0].name}")

    return all_passed


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="Build HCode with Cython compilation")
    parser.add_argument("--pkg", action="store_true", help="Build only Python package")
    parser.add_argument("--exe", action="store_true", help="Build only executable")
    parser.add_argument("--clean", action="store_true", help="Clean build artifacts only")
    parser.add_argument("--no-verify", action="store_true", help="Skip verification")
    parser.add_argument(
        "--no-compile", action="store_true", help="Skip Cython compilation (use existing)"
    )
    args = parser.parse_args()

    print("=" * 60)
    print("  HCode Cython Build")
    print("=" * 60)

    # Clean only
    if args.clean:
        clean_build_artifacts()
        return 0

    # If no specific target, build both
    build_pkg = args.pkg or (not args.pkg and not args.exe)
    build_exe = args.exe or (not args.pkg and not args.exe)

    # Check Cython
    if not check_cython():
        print("\nInstall Cython with: pip install cython")
        return 1

    # Clean previous builds
    clean_build_artifacts()

    # Compile with Cython
    if not args.no_compile:
        if not compile_with_cython():
            print("\nCython compilation failed!")
            return 1

    # Build package
    if build_pkg:
        # Check if build module is available
        try:
            import build
        except ImportError:
            print("Installing build module...")
            subprocess.run([sys.executable, "-m", "pip", "install", "build"], capture_output=True)

        if not build_cython_package():
            print("\nPackage build failed!")
            return 1

    # Build executable
    if build_exe:
        # Check if PyInstaller is available
        try:
            import PyInstaller
        except ImportError:
            print("Installing PyInstaller...")
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "pyinstaller"], capture_output=True
            )

        if not build_cython_exe():
            print("\nExecutable build failed!")
            return 1

    # Verify
    if not args.no_verify:
        if not verify_builds():
            print("\nVerification failed!")
            return 1

    print("\n" + "=" * 60)
    print("  BUILD SUCCESSFUL!")
    print("=" * 60)
    print(f"\nOutput directory: {DIST_DIR / 'compiled'}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
